name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Rust binary
        run: cargo build --release
        working-directory: crud
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-binary
          path: crud/target/release/my-binary

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-binary
      - name: Set executable permissions
        run: chmod +x my-binary
      - name: Run binary
        run: sh -c './my-binary'